### ISSUE TITLE
different query parameters

### ISSUE THREAD

**Issue by cschacht** [werthdavid/homebridge-weather#1]
Hi,
great stuff this! 

I just wonder if you could include different query parameters for more accurate results? Like city ID; zip code or (better) geo coordinates?

Also is there a way to get other info returned by weathermap especially rain and wind data?

Regards
Christian

**Comment by silvetti** [comment]
Also interested in this.

**Comment by werthdavid** [comment]
Hey,

using a different query parameter should not be a problem, I'll check on that!

Returning different info than temperature is more problematic in my opinion. Homekit seems not to be offering sensors for that. I could adapt the plugin to return rain/wind data as temperature but as you might have noticed that Homekit always rounds the numbers (0.9km/h wind speed --> 0 "degrees"). Also "3h rain" would become 3 "degrees". Is that interesting anyways?
