### ISSUE TITLE
Different names for Temperature and Humidity

### ISSUE THREAD

**Issue by honkmaster** [werthdavid/homebridge-weather#11]
Would it be possible to add a configuration option to have different names for the temperature and humidity sensor? Would be very useful. Thanks.

**Comment by werthdavid** [comment]
Please test with the latest version (1.5.0)

**Comment by honkmaster** [comment]
Man, you are quick. Will try it this evening. Danke.

**Comment by honkmaster** [comment]
Works as expected.
