### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by cuiyihaohao** [werthdavid/homebridge-weather#12]
I've got some errors using this project lately.
![qq 20180128202010](https://user-images.githubusercontent.com/30082667/35481950-acb840c2-0468-11e8-8714-93bd39ba92c5.png)。

**Comment by cuiyihaohao** [comment]
![qq 20180128202518](https://user-images.githubusercontent.com/30082667/35481999-a870173c-0469-11e8-841d-b852077b2295.png)
config.json

**Comment by werthdavid** [comment]
In your config you are 'missing' an accessory with the type **current**. At this point, min and max only work if you also define a sensor for the current temperature. Would it be a problem for you to add that?

**Comment by cuiyihaohao** [comment]
thank you very much.But I try to modify config.json like you said, but still have the same bug.
![qq 20180130231344](https://user-images.githubusercontent.com/30082667/35573939-7230f9ce-0613-11e8-85c5-74ccb687a5c6.png)

![qq 20180130230503](https://user-images.githubusercontent.com/30082667/35573759-edaddf78-0612-11e8-9b31-b724db0947af.png),

**Comment by werthdavid** [comment]
Did you install the latest version (currently 1.6.2) yet? Could you please parse the config here, so I can copy it. Thanks

**Comment by cuiyihaohao** [comment]
Thanks for your patience.yeah,i install the latest version today,but there are still the same mistakes.

  "accessories":[
    {
      "accessory":"Weather",
      "apikey":"***",
      "locationById": "1796236",
      "name":"Current Temp",
      "nameHumidity":"Current Humidity",
      "pollingInterval":"10",
      "type":"current"
    },
    {
      "accessory":"Weather",
      "apikey":"***",
     "locationById": "1796236",
      "name":"Today Min",
      "type":"min"
    },
    {
      "accessory":"Weather",
      "apikey":"***",
      "locationById": "1796236",
      "name":"Today Max",
      "type":"max"
    }
  ]

**Comment by werthdavid** [comment]
That's weird... when I paste your config it works just fine with my setup.
The problem seems to be that the response is not in the correct format.
Can you try removing the max-sensor from the config and see what happens?

**Comment by martinnock** [comment]
Do you get this error both in locationbycoordinates and locationbyid mode?

**Comment by cuiyihaohao** [comment]
yeah, i think you are right. I try to remove the max -sensor. But there are still errors.
 temperature= parseFloat(this.cachedWeatherObj["list"][0]["temp"]["min"]);
 TypeError: Cannot read property '0' of undefined
...
 i cant understand why it runs perfectly on your device.I try to solve the problem by reloaded the system.But the it never worked if i added the "max" or "min".
thank you

**Comment by werthdavid** [comment]
Please add the min- and max-sensors again and update to the latest version 1.6.4. I've added a debug output that logs the server-response.

After the Bridge has crashed, please provide the [homebridge.log](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting)

**Comment by cuiyihaohao** [comment]
thank you very much . The problem has been solved by reading the homebridge.log. API is invalid.I changed it and the project worked very well.Thanks again for your patience
