### ISSUE TITLE
Enhancement: Add history to weather sensors

### ISSUE THREAD

**Issue by honkmaster** [werthdavid/homebridge-weather#13]
Using `fakegato-history`, you can simply add a history functionality to your sensors. The history, then will be available in the Elgato Eve App. I first seen this feature in `homebridge-dht`, and really like it.

See: https://github.com/simont77/fakegato-history

**Comment by werthdavid** [comment]
I can try to include it but won't be able to test it

**Comment by honkmaster** [comment]
Would be really appreciated. I will test it surely, additionally I'm looking into node.JS myself. Next time I will submit a PR :).... Greetings.

**Comment by werthdavid** [comment]
Can you try it with the latest version (1.6.0) and let me know if it works?

**Comment by honkmaster** [comment]
It does not seem to work. I used:

```
"pollingInterval": "1",
"enableHistory": true
```

Maybe there is an error in line 186. I don't know if `temperature: temperature` is valid, as the sample uses `temp: `, see:

`  this.loggingService.addEntry({time: moment().unix(), temp:this.temperature, pressure:this.airPressure, humidity:this.humidity});`

Maybe you can compare with `homebridge-dht`: https://github.com/NorthernMan54/homebridge-dht/blob/master/index.js. This is working in Eve.

**Comment by werthdavid** [comment]
Good point... maybe now?

**Comment by honkmaster** [comment]
It is working. Thanks. One minor issue, the first value for temp is zero degrees. 

![img_7989](https://user-images.githubusercontent.com/1380397/35574322-ca0b8d9c-05d9-11e8-844e-0bf44bb68940.PNG)

**Comment by honkmaster** [comment]
Same is true after a restart of `homebridge` (for both tamp and humidity). Maybe only report valid data from cache. 

![img_7990](https://user-images.githubusercontent.com/1380397/35574751-ef0a515e-05da-11e8-824e-b9c4fdccf5e7.PNG)

**Comment by werthdavid** [comment]
Should be fixed with 1.6.2

Cool feature actually!

**Comment by werthdavid** [comment]
@honkmaster could you please test if it still works with 1.6.3? Don't know how homebridge behaves with potential undefined values...

**Comment by honkmaster** [comment]
There is no initial jump in the graph, seems to work. If you want, i can provide a screenshot after logging has taken place for a few days ...

**Comment by werthdavid** [comment]
Yes please, that would be cool! Thanks

**Comment by werthdavid** [comment]
![eve-example](https://user-images.githubusercontent.com/4696067/35668836-601c4a10-0733-11e8-982e-fa2a406a46e7.jpg)

Got one :wink: But thanks!
Really cool feature!
