### ISSUE TITLE
Can't get max or min temp

### ISSUE THREAD

**Issue by nwoodman** [werthdavid/homebridge-weather#14]
A very handy app however.  Thee "current" temp works a treat however I can't get "max" or "min" temps to work

/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:157
                    temperature = parseFloat(this.cachedWeatherObj["list"][0]["temp"]["min"]);
                                                                          ^

TypeError: Cannot read property '0' of undefined
    at WeatherAccessory.returnTempFromCache (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:157:75)
    at WeatherAccessory.setCacheObj (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:145:36)
    at WeatherAccessory.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:104:30)
    at Request._callback (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:271:21)
    at Request.self.callback (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:127:13)
    at IncomingMessage.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by werthdavid** [comment]
Can you provide your config please? Make sure to remove the API-key before posting it though 😉

**Comment by nwoodman** [comment]
Here it is.  Changing current to max gives rise to the error

```json
{
	"bridge": {
		"name": "Homebridge2",
		"username": "CC:22:3D:E3:CE:41",
		"port": 51827,
		"pin": "031-45-161"

	},
	"accessories": [
	{
	"accessory": "Weather",
		"apikey": "****",
		"locationByCoordinates": "lat=-37.805212&lon=145.103224",
		"name": "OpenWeather",
		"type":"current"
				
},
{
   	"accessory": "OnkyoAVR",
   	"name": "My Onkyo",
   	"ip_address": "192.168.0.55",
   	"model" : "TX-NR609",
   	"poll_status_interval": "1500"
   }



]
}
```

**Comment by werthdavid** [comment]
Can you please try it with the following config (after changing the API-key) and tell me what happens

```json
{
   "bridge":{
      "name":"Homebridge2",
      "username":"CC:22:3D:E3:CE:41",
      "port":51827,
      "pin":"031-45-161"
   },
   "accessories":[
      {
         "accessory":"Weather",
         "apikey":"***",
         "locationByCoordinates":"lat=-37.805212&lon=145.103224",
         "name":"Aktuell",
         "nameHumidity":"Luftfeuchtigkeit",
         "pollingInterval":"10",
         "enableHistory":true
      },
      {
         "accessory":"Weather",
         "apikey":"***",
         "locationByCoordinates":"lat=-37.805212&lon=145.103224",
         "name":"Min",
         "type":"min"
      },
      {
         "accessory":"Weather",
         "apikey":"***",
         "locationByCoordinates":"lat=-37.805212&lon=145.103224",
         "name":"Max",
         "type":"max"
      },
      {
         "accessory":"OnkyoAVR",
         "name":"My Onkyo",
         "ip_address":"192.168.0.55",
         "model":"TX-NR609",
         "poll_status_interval":"1500"
      }
   ]
}
```

**Comment by nwoodman** [comment]
Thanks David.,

This is what I got back

[2018-3-5 20:40:54] [Aktuell] Fetched temperature 17 of type current for Aktuell
[2018-3-5 20:40:54] [Aktuell] Fetched humidity 48 of type current for Aktuell
[2018-3-5 20:40:54] [Aktuell] Fetched temperature 17 of type current for Aktuell
[2018-3-5 20:40:54] [Aktuell] Fetched temperature 17 of type current for Aktuell
[2018-3-5 20:40:54] [Aktuell] Fetched humidity 48 of type current for Aktuell
[2018-3-5 20:40:54] [Aktuell] Fetched humidity 48 of type current for Aktuell
/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:157
                    temperature = parseFloat(this.cachedWeatherObj["list"][0]["temp"]["min"]);
                                                                          ^

TypeError: Cannot read property '0' of undefined
    at WeatherAccessory.returnTempFromCache (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:157:75)
    at WeatherAccessory.setCacheObj (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:145:36)
    at WeatherAccessory.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:104:30)
    at Request._callback (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:271:21)
    at Request.self.callback (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:186:22)
    at Request.emit (events.js:127:13)
    at Request.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:127:13)
    at IncomingMessage.<anonymous> (/home/nigel/.npm-global/lib/node_modules/homebridge-weather/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:219:13)
    at IncomingMessage.emit (events.js:132:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

Cheers

Nigel

**Comment by werthdavid** [comment]
Please update your config again

```json
{
   "bridge":{
      "name":"Homebridge2",
      "username":"CC:22:3D:E3:CE:41",
      "port":51827,
      "pin":"031-45-161"
   },
   "accessories":[
      {
         "accessory":"Weather",
         "apikey":"***",
         "locationByCoordinates":"lat=-37.805212&lon=145.103224",
         "name":"Min",
         "type":"min"
      },
      {
         "accessory":"Weather",
         "apikey":"***",
         "locationByCoordinates":"lat=-37.805212&lon=145.103224",
         "name":"Max",
         "type":"max"
      },
      {
         "accessory":"OnkyoAVR",
         "name":"My Onkyo",
         "ip_address":"192.168.0.55",
         "model":"TX-NR609",
         "poll_status_interval":"1500"
      }
   ]
}
```

And then enable debugging according to [the docs](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting). I would then need the log file that can be found in /var/log/homebridge.log

**Comment by nwoodman** [comment]
OK I think that was a very helpful exercise

I ran

DEBUG=* homebridge -U ~/.homebridge2 -D

Unfortunately it didn’t write a log file but it did do a screen dump


The full dump is below, but I did glean this line from it

[2018-3-5 20:59:08] [Max] Server response: {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}
/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:159
                    temperature = parseFloat(this.cachedWeatherObj["list"][0]["temp"]["max"]);

Does this mean I need a different API?

Let me just thank you in advance for your help on this, I am coming from a  really low base 😊

Cheers

Nigel





Full log


[2018-3-5 20:58:54] [homebridge-dyson-link.DysonPlatform] Finished launching. Start to create accessory from config
  EventedHTTPServer Server listening on port 51827 +0ms
[2018-3-5 20:58:54] Homebridge is running on port 51827.
[2018-3-5 20:58:54] [My Onkyo] start polling..
  polling-to-event Emitting 'poll'. +0ms
  polling-to-event Comparing last polled parameters +2ms
  polling-to-event Last polled data and previous poll data are not equal. +1ms
  polling-to-event Emitting 'statuspoll'. +1ms
[2018-3-5 20:58:54] [My Onkyo] event - status poller - new state:  false
[2018-3-5 20:58:54] [My Onkyo] setPowerState - polling mode, ignore, state: false
[2018-3-5 20:58:54] [My Onkyo] getVolume - actual mode, oldValue: 0
[2018-3-5 20:58:54] [My Onkyo] getPowerState - actual mode, return state:  false
[2018-3-5 20:58:54] [My Onkyo] eventConnect: 192.168.0.55
[2018-3-5 20:58:54] [My Onkyo] eventConnect: 192.168.0.55
[2018-3-5 20:58:54] [My Onkyo] eventVolume: 52
[2018-3-5 20:58:54] [My Onkyo] setVolume - polling mode, ignore, volume: 52
[2018-3-5 20:58:54] [My Onkyo] eventSystemPower - message: on, new state true
[2018-3-5 20:58:54] [My Onkyo] setPowerState - polling mode, ignore, state: true
  EventedHTTPServer [::ffff:192.168.0.78] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.0.78] HTTP server listening on port 39915 +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /pair-verify +12ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +7ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +26ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /pair-verify +22ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +2ms
  HAPServer [CC:22:3D:E3:CE:41] Client AD19043F-FADB-4DF2-BA8D-423A7B0C3DC3 verification complete +5ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /accessories +9ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.0.164] New connection from client +99ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP server listening on port 38577 +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +8ms
  EventedHTTPServer [::ffff:192.168.0.207] New connection from client +1ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP server listening on port 42315 +1ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.0.144] New connection from client +1ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP server listening on port 45927 +1ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client AD19043F-FADB-4DF2-BA8D-423A7B0C3DC3 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /characteristics +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":13,"iid":10,"ev":true}] +2ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +2ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client 1F59F10C-1A3D-4606-A436-517F1A162F7F verification complete +3ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /characteristics +2ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":12,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /accessories +0ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.0.207] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP request: /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client 97B3C51E-9B8A-4595-93EB-B3743E1EF0D1 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP request: /characteristics +5ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":7,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.78] HTTP Response is finished +1ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] New connection from client +1ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP server listening on port 36773 +1ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +2ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.0.74] New connection from client +2ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP server listening on port 46143 +0ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP request: /accessories +2ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.144] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.0.215] New connection from client +6ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP server listening on port 36717 +1ms
  EventedHTTPServer [::ffff:192.168.0.8] New connection from client +1ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP server listening on port 33419 +1ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP Response is finished +7ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client 97B3C51E-9B8A-4595-93EB-B3743E1EF0D1 verification complete +3ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +0ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP Response is finished +8ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client AD19043F-FADB-4DF2-BA8D-423A7B0C3DC3 verification complete +2ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /characteristics +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":12,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +0ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP request: /accessories +3ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.74] HTTP Response is finished +3ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP request: /accessories +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [fe80::185b:9d80:dbff:f715] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /pair-verify +12ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client AD19043F-FADB-4DF2-BA8D-423A7B0C3DC3 verification complete +2ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP request: /pair-verify +1ms
 HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client 1974BB84-9097-4988-88F3-FB344515F8F5 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /characteristics +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":7,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP request: /accessories +8ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.8] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP request: /characteristics +13ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":13,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +0ms
  EventedHTTPServer [::ffff:192.168.0.164] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /characteristics +76ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":12,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /characteristics +5ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":13,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP request: /characteristics +5ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":7,"iid":10,"ev":true}] +0ms
  Accessory [Homebridge2] Registering Characteristic "On" for events +0ms
  EventedHTTPServer [::ffff:192.168.0.215] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.163] New connection from client +10s
  EventedHTTPServer [::ffff:192.168.0.163] HTTP server listening on port 41531 +0ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /pair-verify +4ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished +8ms
  EventedHTTPServer [fe80::c1a:25cc:96c7:6079] New connection from client +1ms
  EventedHTTPServer [fe80::c1a:25cc:96c7:6079] HTTP server listening on port 41299 +1ms
  EventedHTTPServer [fe80::c1a:25cc:96c7:6079] Client connection closed +6ms
  EventedHTTPServer [fe80::c1a:25cc:96c7:6079] HTTP connection was closed +1ms
  EventedHTTPServer [fe80::c1a:25cc:96c7:6079] HTTP server was closed +3ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /pair-verify +17ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +0ms
  HAPServer [CC:22:3D:E3:CE:41] Client 97B3C51E-9B8A-4595-93EB-B3743E1EF0D1 verification complete +3ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP request: /accessories +7ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.0.163] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.34] New connection from client +350ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP server listening on port 35799 +0ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP Response is finished +11ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP request: /pair-verify +16ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client 1974BB84-9097-4988-88F3-FB344515F8F5 verification complete +16ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP request: /accessories +5ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.34] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.51] New connection from client +167ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP server listening on port 44021 +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 1/2 +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +18ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /pair-verify +46ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:41] Pair verify step 2/2 +1ms
  HAPServer [CC:22:3D:E3:CE:41] Client AD19043F-FADB-4DF2-BA8D-423A7B0C3DC3 verification complete +10ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /accessories +4ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /characteristics +991ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":7,"iid":10,"ev":true}] +8ms
  Accessory [Homebridge2] Registering Characteristic "On" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /characteristics +4ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":13,"iid":10,"ev":true}] +4ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /characteristics +4ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge2] Processing characteristic set: [{"aid":12,"iid":10,"ev":true}] +1ms
  Accessory [Homebridge2] Registering Characteristic "Current Temperature" for events +6ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.0.51] HTTP request: /characteristics?id=13.10,7.10,12.10 +202ms
  HAPServer [CC:22:3D:E3:CE:41] HAP Request: GET /characteristics?id=13.10,7.10,12.10 +1ms
  Accessory [Homebridge2] Getting value for Characteristic "Current Temperature" +2ms
  Accessory [Homebridge2] Getting value for Characteristic "On" +19ms
[2018-3-5 20:59:08] [My Onkyo] getPowerState - polling mode, return state:  true
  Accessory [Homebridge2] Got Characteristic "On" value: true +2ms
  Accessory [Homebridge2] Getting value for Characteristic "Current Temperature" +0ms
[2018-3-5 20:59:08] [Max] Server response: {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}
/home/nigel/.npm-global/lib/node_modules/homebridge-weather/index.js:159
                    temperature = parseFloat(this.cachedWeatherObj["list"][0]["temp"]["max"]);

**Comment by werthdavid** [comment]
Okay no problem.
Did you sign-up [here](https://openweathermap.org/appid)?

**Comment by nwoodman** [comment]
Just on their site now.  Looks like I signed up for current weather data only but will try and subscribe to the 5 day forecast.  It all makes sense now 😊.

Cheers

Nigel



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by nwoodman** [comment]
Actually it doesn’t make sense, my API seems to work when I append it to their URL

http://api.openweathermap.org/data/2.5/forecast?id=524901&APPID=***

I will blow up this API after we figure it out, hence the post above

cheers

Nigel

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by werthdavid** [comment]
Interesting.... Actually the Plugin uses a slightly different URL. Its not /forecast but /forecast/daily. This doesn't work with your API-Key but with mine it does work.

**Comment by nwoodman** [comment]
Sweet, is there a work around?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by werthdavid** [comment]
Working on it!

**Comment by nwoodman** [comment]
Cheers these might be helpful

https://github.com/openhab/openhab1-addons/issues/5309

https://community.openhab.org/t/weather-binding-api-key-error-with-openweathermap/38078




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by werthdavid** [comment]
I just published 1.7.0, please test if it works.
I still don't understand why it works with my API key (I have a free plan) and nobody was complaining before....

**Comment by nwoodman** [comment]
Yep, worked a treat.  Thanks so much

Cheers

Nigel

**Comment by werthdavid** [comment]
@nwoodman there was still an error with max/min, please update to 1.7.1 otherwise min/max is shown not for today but for the next 5 days

**Comment by nwoodman** [comment]
Awesome, its been hot in Oz, so the numbers seemed right.  Thanks for taking time out to let me know

Regards
Nigel Woodman
Mb:0408108018


On 12 Mar 2018, at 7:19 pm, David Werth <notifications@github.com<mailto:notifications@github.com>> wrote:


@nwoodman<https://github.com/nwoodman> there was still an error with max/min, please update to 1.7.1 otherwise min/max is shown not for today but for the next 5 days
