### ISSUE TITLE
Enhancement: Noon value

### ISSUE THREAD

**Issue by sejoki** [werthdavid/homebridge-weather#16]
Thanks for adding the high/low forecast. I have yet another idea for an enhancement, may be a little harder to implement though.

I recently upgraded my window shades to be motorized and HomeKit controlled. So far, they’re pretty dumb - they go up in the morning and down when the sun sets. I’ve been thinking about adding a light sensor to the mix, but I know from experience that it gets pretty annoying because on cloudy summer days, they go up and down all the time.

Sunrise and sunset are pretty reliable, but HomeKit doesn’t have a trigger value for noon. In most cases, this would go a long way. For east oriented windows, the sun won’t hit them after noon, and for west oriented windows, it won’t hit it before.

I know even openweathermap doesn’t provide a specific noon value, though I guess adding the Unix time for sunrise and sunset, then dividing by 2 would give the average. So that wouldn’t be tricky. 
Publishing it to HomeKit though would. Some plugins use a door sensor (calendar for example), if the event is triggered, the door is „open“. Not the cleanest solution imo. Another idea would be a humidity sensor - pretty much displaying the value of how high the sun is currently - 50% would reflect noon in this case. Or another „temperature“ sensor reaching from 0 to 180 degrees with 90 being mid day. 
The last two would require a little more math, but give the option for an offset (e.g. 40% as „noon“ value)

Let me know what you think - I don’t know if this fits into the intended purpose for your plugin or seems reasonable for you to implement. Unfortunately, I don’t know enough about java to do my own plugin, though it may be worth learning.

**Comment by werthdavid** [comment]
I like the idea! Give me a little bit time to think about it but I think I'd like to go with the humidity sensor so it will publish a value between 0 and 100%. Or do you see any advantages of temperature between 0 and 180?

**Comment by werthdavid** [comment]
Please try with 1.8.0

**Comment by sejoki** [comment]
Wow, that was quick! Works perfectly at least with my tests so far (by the way, trying to switch on a light bulb with a 1% increment takes waay longer than expected). Now in theory, I can leave the blinds shut in the morning and raise them once the sun has passed my building, I'll see tomorrow.

I'm pretty lazy (well, I guess we all are, or we wouldn't spend any effort on home automation) and usually in the summer, I'd just leave them shut in the morning and when I got home after work there would only be a couple of hours left, so why raise them just to shut them two hours later? So they just used to stay shut all day during the week…

Thank you :D
