### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liangliangyy** [werthdavid/homebridge-weather#18]
body: '{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}' } {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}

**Comment by ghost** [comment]
Hi, how did you solve this issue? I'm using an API key copied from `https://home.openweathermap.org/api_keys` and pasted into my config.json under the `apikey` key. It gives me the same error you had.

**Comment by ghost** [comment]
Hmm, it fixed itself
