### ISSUE TITLE
Temperature options

### ISSUE THREAD

**Issue by kbiswell** [werthdavid/homebridge-weather#19]
Is there a way to display the temperature in degrees F instead of C?

**Comment by werthdavid** [comment]
Currently not.. I will implement it when I find time, maybe this weekend

**Comment by kbiswell** [comment]
That would be great. Thank you.

**Comment by werthdavid** [comment]
Please test with latest 1.9.0 by adding
"unit": "imperial" 
to your config

**Comment by kbiswell** [comment]
Works perfectly. Thank you

Sent from my iPhone

On Jun 11, 2018, at 12:46 AM, David Werth <notifications@github.com<mailto:notifications@github.com>> wrote:


Please test with latest 1.9.0
