### ISSUE TITLE
Unit Imperial - not correct

### ISSUE THREAD

**Issue by intrepidsilence** [werthdavid/homebridge-weather#20]
I am using imperial units as spelled out in the docs but the value is too high (currently reading 183).  Any ideas why this is happening?

**Comment by werthdavid** [comment]
With my location it works fine.. Can you please paste your config here? Remember to remove the API-key when you paste it

**Comment by intrepidsilence** [comment]
{
            "accessory": "Weather",
            "apikey": "XXXXXXXXXXXXXXXXXXXXXXX",
            "locationById": "4472687",
            "unit": "imperial",
            "name": "Outside Temp"
        }

**Comment by werthdavid** [comment]
Okay I've found the problem... It seems that your device is set to Fahrenheit. Then the Homebridge returns value as Fahrenheit. HomeApp now converts the unit AGAIN. So what you have to do is just remove the unit-setting in your config, HomeApp will take care of everything else. I'll update the Readme.
Your config should look like this:

```
 {
        "accessory": "Weather",
        "apikey": "XXXXXXXXXXXXXXXXXXXXXXX",
        "locationById": "4472687",
        "name": "Outside Temp"
    }
```

**Comment by intrepidsilence** [comment]
Thant works thanks. I swear it was not working when I first installed it and that was why I added the imperial flag. Oh well. Sorry for the confusion.
