### ISSUE TITLE
iOS 13

### ISSUE THREAD

**Issue by Catta1997** [werthdavid/homebridge-weather#21]
with ios 13 humidity and temperature are grouped. is it possible to group all together? it is sufficient to have the same serial number

**Comment by werthdavid** [comment]
thanks for the info, I'll do that

**Comment by werthdavid** [comment]
Please try the latest version, I'm curious if it works :)

**Comment by Catta1997** [comment]
Unfortunately no, maybe iOS checks something else or maybe there is a limit of one humidity sensor on each group

**Comment by werthdavid** [comment]
hm have you seen any other homebridge-plugin that supports it where I could look into the code?

**Comment by werthdavid** [comment]
Grouping seems to automatically happen based on how many "services" one accessory publishes. Sorry, don't see any possibility to help with that
