### ISSUE TITLE
Issues after Elgato Eve app update Ver3.8.1

### ISSUE THREAD

**Issue by ddong3000** [werthdavid/homebridge-weather#22]
Temperature profile with Elgato Eve App feature is disabled
please check
My iOS is ios13.1 public beta

**Comment by werthdavid** [comment]
https://github.com/simont77/fakegato-history/issues/76

**Comment by ExhaleSthlm** [comment]
Hi!
The Windspeed seems broken, looking at the code there seems to be a cut and paste error:

if (this.type === "windspeed") {
                this.getStateSun(function (error, value) {
                    if (!error && value != null) {
                        humidityService.setCharacteristic(Characteristic.CurrentRelativeHumidity, value);
                    }
                }.bind(this));
            }

**Comment by werthdavid** [comment]
Yes you are right.. will fix that ASAP!

**Comment by werthdavid** [comment]
It should work now with 1.12.1

**Comment by werthdavid** [comment]
homebridge-weather@1.12.2
