### ISSUE TITLE
Split Temperature and Humadity in two Devices

### ISSUE THREAD

**Issue by timwegenerDE** [werthdavid/homebridge-weather#23]
Das Plugin funktioniert super, bin begeistert :)

Ich würde mir gerne die Luftfeuchtigkeit und die Temperatur jeweils als einzelnes Gerät darstellen lassen, damit ich die Werte direkt in der Home-Übersicht sehe; Aktuell steht hier nur „2 Sensoren“. Am einfachsten wäre wohl eine Option in der config:
`showtemperature:false`. Hiermit ließe sich ein Gerät zur Temperatur uns eins für die Luftfeuchtigkeit hinzufügen.

**Comment by werthdavid** [comment]
Ja seit iOS 13 ist das sonst ein bisschen umständlich.. sollte kein Problem sein ich kümmere mich darum

**Comment by werthdavid** [comment]
bitte mit 1.11.0 versuchen ;-)

**Comment by timwegenerDE** [comment]
Funktioniert auf Anhieb!

Super - Danke für die schnelle Umsetzung :)

**Comment by werthdavid** [comment]
https://www.iphone-ticker.de/ios-13-2-homekit-wieder-mit-separaten-kacheln-147865/
