### ISSUE TITLE
Cloudiness reported as Humidity

### ISSUE THREAD

**Issue by appliko** [werthdavid/homebridge-weather#28]
In general it works well but Cloudiness is reported as Humidity. This makes it unusable for status message
Is it an issue or something can be fixed by configuration ?

My configuration entry is

      "accessory" : "Weather",
      "name" : "Cloudiness",
      "type" : "clouds",
      "location" : "my city",
      "apikey" : "my api key"

Thanks

**Comment by werthdavid** [comment]
Hey there,
the problem is that homebridge/HAP doesn't offer a sensor for cloudiness. therefore I used a humidity-sensor that provides the cloudiness data. what exactly are you trying? I'm not sure what you mean by "status message"..

**Comment by appliko** [comment]
I mean status message on main panel of Home app on iOS

**Comment by appliko** [comment]
Ok, understood, just removed from status - thanks !
