### ISSUE TITLE
Cloudiness is steady at 75%

### ISSUE THREAD

**Issue by jchristianj** [werthdavid/homebridge-weather#29]
For the last few days or maybe one week the cloudiness value is 75% all the time... sometimes it updates to another value, but in most cases when I look it up it is 75% which does not reflect the actual status of the sky in my location. 
Is there any issue with fetching the value for cloudiness? All other data is polled correctly and updates / changes. See log file:

[Homebridge] [1/3/2020, 22:50:29] [Wetter] Fetched temperature value 5.08deg of type 'current' for accessory Wetter
[Homebridge] [1/3/2020, 22:50:29] [Bewölkung] Fetched cloudiness value 75% of type 'clouds' for accessory Bewölkung
[Homebridge] [1/3/2020, 22:50:29] [Wetter] Fetched humidity value 93% of type 'current' for accessory Wetter

configuration file section:
 {
            "accessory": "Weather",
            "name": "Wetter",
            "locationByCoordinates": "lat=51.000000&lon=6.000000",
            "apikey": "this_is_secret",
            "pollingInterval": 5,
            "plugin_map": {
                "plugin_name": "homebridge-weather",
                "index": 0
            }
        },
        {
            "accessory": "Weather",
            "name": "Bewölkung",
            "type": "clouds",
            "locationByCoordinates": "lat=51.000000&lon=6.000000",
            "apikey": "this_is_secret",
            "pollingInterval": 5,
            "plugin_map": {
                "plugin_name": "homebridge-weather",
                "index": 0
            }
        },

Any idea or anyone experiencing the same?

Christian

**Comment by werthdavid** [comment]
Can you provide the Log with debugging enabled? 
See [here](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting)

**Comment by jchristianj** [comment]
Hi! I’m running the plugin on hoobs. Not sure how to get logs in debug mode there...

**Comment by werthdavid** [comment]
Oh wow I didn't know hoobs did exist.

Here is a link with some information:

https://github.com/hoobs-org/HOOBS/wiki/6.2-Command-Line-Interface

**Comment by jchristianj** [comment]
Thanks, David. 
Sorry, cannot get detailed logs from hoobs. It is not giving more details when using the command line interface, there is something in my network preventing getting the logs more detailed. Yeah, hoobs is the right thing for me as it makes homebridge usable even for dummies like me...
Anyhow, in the last few days I compared the cloudiness value which is read from your plugin with the cloudiness value which is shown on openweather.org website: It is identical. So the plugin seems to be working correctly. So when I feel that cloudiness does not fit to the actual condition, then it might be a flaw in the data source, but not in the plugin. 
Thanks anyway!

**Comment by werthdavid** [comment]
Oh okay thanks for the information. How do you find your location? I could imagine that is you use lat/lon that the values are not always as reliable as if you use a city. I'm not sure if there is a list of the actual weather stations around you

**Comment by werthdavid** [comment]
https://openweathermap.org/weathermap?basemap=map&cities=true&layer=temperature&lat=48.9315&lon=9.4098&zoom=10

When I look at the map almost all cities in South Germany give me 75% cloudiness.... In the north it shows 90% sometimes. I have no idea where those values come from though

**Comment by jchristianj** [comment]
It's odd, in my location it is mostly 75% or 90%... nothing in between, very seldom below or above.
I am using the LocationByCoordinates parameter. For testing I changed to location to city name, it made no difference.
