### ISSUE TITLE
Wind sensor doesn't work

### ISSUE THREAD

**Issue by Julien-Molina** [werthdavid/homebridge-weather#31]
I don't know why but my wind sensor is not showing any data.

Here is my configuration for this sensor : 
{
            "accessory": "Weather",
            "apikey": "**********",
            "location": "Paris,fr",
            "name": "Wind",
            "type": "windspeed"
}

Logs : 
[Wind] Server response: {"cod":"200","message":0,"cnt":40,"list":[{"dt":1588593600,"main":{"temp":18.24,"feels_like":17.3,"temp_min":18.24,"temp_max":20.66,"pressure":1018,"sea_level":1017,"grnd_level":1012,"humidity":61,"temp_kf":-2.42},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":85},"wind":{"speed":1.64,"deg":24},"sys":{"pod":"d"},"dt_txt":"2020-05-04 12:00:00"},{"dt":1588604400,"main":{"temp":19.19,"feels_like":16.72,"temp_min":19.19,"temp_max":20.09,"pressure":1016,"sea_level":1016,"grnd_level":1011,"humidity":55,"temp_kf":-0.9},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":98},"wind":{"speed":3.57,"deg":45},"sys":{"pod":"d"},"dt_txt":"2020-05-04 15:00:00"},{"dt":1588615200,"main":{"temp":17.39,"feels_like":14.36,"temp_min":17.39,"temp_max":17.49,"pressure":1016,"sea_level":1016,"grnd_level":1011,"humidity":64,"temp_kf":-0.1},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":99},"wind":{"speed":4.59,"deg":61},"sys":{"pod":"d"},"dt_txt":"2020-05-04 18:00:00"},{"dt":1588626000,"main":{"temp":14.79,"feels_like":11.2,"temp_min":14.78,"temp_max":14.79,"pressure":1017,"sea_level":1017,"grnd_level":1012,"humidity":69,"temp_kf":0.01},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":97},"wind":{"speed":4.87,"deg":64},"sys":{"pod":"n"},"dt_txt":"2020-05-04 21:00:00"},{"dt":1588636800,"main":{"temp":13.3,"feels_like":9.22,"temp_min":13.3,"temp_max":13.3,"pressure":1018,"sea_level":1018,"grnd_level":1012,"humidity":68,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":99},"wind":{"speed":5,"deg":72},"sys":{"pod":"n"},"dt_txt":"2020-05-05 00:00:00"},{"dt":1588647600,"main":{"temp":12.19,"feels_like":7.26,"temp_min":12.19,"temp_max":12.19,"pressure":1015,"sea_level":1015,"grnd_level":1010,"humidity":68,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":100},"wind":{"speed":5.87,"deg":74},"sys":{"pod":"n"},"dt_txt":"2020-05-05 03:00:00"},{"dt":1588658400,"main":{"temp":12.01,"feels_like":7.35,"temp_min":12.01,"temp_max":12.01,"pressure":1015,"sea_level":1015,"grnd_level":1010,"humidity":65,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":100},"wind":{"speed":5.23,"deg":78},"sys":{"pod":"d"},"dt_txt":"2020-05-05 06:00:00"},{"dt":1588669200,"main":{"temp":14.47,"feels_like":9.84,"temp_min":14.47,"temp_max":14.47,"pressure":1016,"sea_level":1016,"grnd_level":1010,"humidity":55,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":100},"wind":{"speed":5.17,"deg":87},"sys":{"pod":"d"},"dt_txt":"2020-05-05 09:00:00"},{"dt":1588680000,"main":{"temp":13.96,"feels_like":11.02,"temp_min":13.96,"temp_max":13.96,"pressure":1016,"sea_level":1016,"grnd_level":1011,"humidity":67,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":100},"wind":{"speed":3.51,"deg":92},"rain":{"3h":0.89},"sys":{"pod":"d"},"dt_txt":"2020-05-05 12:00:00"},{"dt":1588690800,"main":{"temp":14.46,"feels_like":12,"temp_min":14.46,"temp_max":14.46,"pressure":1017,"sea_level":1017,"grnd_level":1012,"humidity":71,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":99},"wind":{"speed":3.3,"deg":51},"rain":{"3h":1.6},"sys":{"pod":"d"},"dt_txt":"2020-05-05 15:00:00"},{"dt":1588701600,"main":{"temp":14.96,"feels_like":12.07,"temp_min":14.96,"temp_max":14.96,"pressure":1017,"sea_level":1017,"grnd_level":1012,"humidity":68,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":93},"wind":{"speed":3.86,"deg":73},"sys":{"pod":"d"},"dt_txt":"2020-05-05 18:00:00"},{"dt":1588712400,"main":{"temp":13.39,"feels_like":11.16,"temp_min":13.39,"temp_max":13.39,"pressure":1019,"sea_level":1019,"grnd_level":1014,"humidity":71,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"clouds":{"all":48},"wind":{"speed":2.6,"deg":37},"sys":{"pod":"n"},"dt_txt":"2020-05-05 21:00:00"},{"dt":1588723200,"main":{"temp":11.81,"feels_like":8.68,"temp_min":11.81,"temp_max":11.81,"pressure":1020,"sea_level":1020,"grnd_level":1015,"humidity":69,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"clouds":{"all":52},"wind":{"speed":3.26,"deg":45},"sys":{"pod":"n"},"dt_txt":"2020-05-06 00:00:00"},{"dt":1588734000,"main":{"temp":10.44,"feels_like":6.79,"temp_min":10.44,"temp_max":10.44,"pressure":1020,"sea_level":1020,"grnd_level":1015,"humidity":58,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":1},"wind":{"speed":2.95,"deg":58},"sys":{"pod":"n"},"dt_txt":"2020-05-06 03:00:00"},{"dt":1588744800,"main":{"temp":10.42,"feels_like":6.54,"temp_min":10.42,"temp_max":10.42,"pressure":1021,"sea_level":1021,"grnd_level":1016,"humidity":50,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":1},"wind":{"speed":2.8,"deg":62},"sys":{"pod":"d"},"dt_txt":"2020-05-06 06:00:00"},{"dt":1588755600,"main":{"temp":15.1,"feels_like":11.14,"temp_min":15.1,"temp_max":15.1,"pressure":1022,"sea_level":1022,"grnd_level":1016,"humidity":42,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":0},"wind":{"speed":3.33,"deg":56},"sys":{"pod":"d"},"dt_txt":"2020-05-06 09:00:00"},{"dt":1588766400,"main":{"temp":19.07,"feels_like":14.4,"temp_min":19.07,"temp_max":19.07,"pressure":1022,"sea_level":1022,"grnd_level":1017,"humidity":31,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":0},"wind":{"speed":4.18,"deg":59},"sys":{"pod":"d"},"dt_txt":"2020-05-06 12:00:00"},{"dt":1588777200,"main":{"temp":19.86,"feels_like":15.73,"temp_min":19.86,"temp_max":19.86,"pressure":1021,"sea_level":1021,"grnd_level":1016,"humidity":33,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":0},"wind":{"speed":3.78,"deg":56},"sys":{"pod":"d"},"dt_txt":"2020-05-06 15:00:00"},{"dt":1588788000,"main":{"temp":17.77,"feels_like":14.06,"temp_min":17.77,"temp_max":17.77,"pressure":1021,"sea_level":1021,"grnd_level":1016,"humidity":42,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":0},"wind":{"speed":3.6,"deg":63},"sys":{"pod":"d"},"dt_txt":"2020-05-06 18:00:00"},{"dt":1588798800,"main":{"temp":14.54,"feels_like":11.69,"temp_min":14.54,"temp_max":14.54,"pressure":1023,"sea_level":1023,"grnd_level":1018,"humidity":57,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0},"wind":{"speed":2.79,"deg":45},"sys":{"pod":"n"},"dt_txt":"2020-05-06 21:00:00"},{"dt":1588809600,"main":{"temp":12.42,"feels_like":10.05,"temp_min":12.42,"temp_max":12.42,"pressure":1023,"sea_level":1023,"grnd_level":1018,"humidity":68,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":2},"wind":{"speed":2.28,"deg":43},"sys":{"pod":"n"},"dt_txt":"2020-05-07 00:00:00"},{"dt":1588820400,"main":{"temp":11,"feels_like":8.76,"temp_min":11,"temp_max":11,"pressure":1023,"sea_level":1023,"grnd_level":1017,"humidity":68,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03n"}],"clouds":{"all":39},"wind":{"speed":1.68,"deg":42},"sys":{"pod":"n"},"dt_txt":"2020-05-07 03:00:00"},{"dt":1588831200,"main":{"temp":11.3,"feels_like":8.89,"temp_min":11.3,"temp_max":11.3,"pressure":1022,"sea_level":1022,"grnd_level":1017,"humidity":62,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"clouds":{"all":65},"wind":{"speed":1.63,"deg":54},"sys":{"pod":"d"},"dt_txt":"2020-05-07 06:00:00"},{"dt":1588842000,"main":{"temp":16.83,"feels_like":13.81,"temp_min":16.83,"temp_max":16.83,"pressure":1022,"sea_level":1022,"grnd_level":1017,"humidity":39,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"clouds":{"all":66},"wind":{"speed":2.12,"deg":67},"sys":{"pod":"d"},"dt_txt":"2020-05-07 09:00:00"},{"dt":1588852800,"main":{"temp":21.03,"feels_like":17.66,"temp_min":21.03,"temp_max":21.03,"pressure":1021,"sea_level":1021,"grnd_level":1016,"humidity":28,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"clouds":{"all":63},"wind":{"speed":2.38,"deg":63},"sys":{"pod":"d"},"dt_txt":"2020-05-07 12:00:00"},{"dt":1588863600,"main":{"temp":21.48,"feels_like":18.24,"temp_min":21.48,"temp_max":21.48,"pressure":1020,"sea_level":1020,"grnd_level":1015,"humidity":30,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":100},"wind":{"speed":2.53,"deg":65},"sys":{"pod":"d"},"dt_txt":"2020-05-07 15:00:00"},{"dt":1588874400,"main":{"temp":19.26,"feels_like":17.04,"temp_min":19.26,"temp_max":19.26,"pressure":1020,"sea_level":1020,"grnd_level":1014,"humidity":41,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":100},"wind":{"speed":1.76,"deg":67},"sys":{"pod":"d"},"dt_txt":"2020-05-07 18:00:00"},{"dt":1588885200,"main":{"temp":16.46,"feels_like":14.81,"temp_min":16.46,"temp_max":16.46,"pressure":1020,"sea_level":1020,"grnd_level":1015,"humidity":51,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":100},"wind":{"speed":1.14,"deg":62},"sys":{"pod":"n"},"dt_txt":"2020-05-07 21:00:00"},{"dt":1588896000,"main":{"temp":14.52,"feels_like":12.87,"temp_min":14.52,"temp_max":14.52,"pressure":1020,"sea_level":1020,"grnd_level":1015,"humidity":57,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"clouds":{"all":66},"wind":{"speed":1.07,"deg":46},"sys":{"pod":"n"},"dt_txt":"2020-05-08 00:00:00"},{"dt":1588906800,"main":{"temp":13,"feels_like":11.11,"temp_min":13,"temp_max":13,"pressure":1019,"sea_level":1019,"grnd_level":1014,"humidity":62,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01n"}],"clouds":{"all":0},"wind":{"speed":1.35,"deg":41},"sys":{"pod":"n"},"dt_txt":"2020-05-08 03:00:00"},{"dt":1588917600,"main":{"temp":13.72,"feels_like":11.9,"temp_min":13.72,"temp_max":13.72,"pressure":1020,"sea_level":1020,"grnd_level":1014,"humidity":60,"temp_kf":0},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"clouds":{"all":9},"wind":{"speed":1.32,"deg":39},"sys":{"pod":"d"},"dt_txt":"2020-05-08 06:00:00"},{"dt":1588928400,"main":{"temp":19.07,"feels_like":16.85,"temp_min":19.07,"temp_max":19.07,"pressure":1019,"sea_level":1019,"grnd_level":1014,"humidity":44,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"clouds":{"all":49},"wind":{"speed":2.02,"deg":57},"sys":{"pod":"d"},"dt_txt":"2020-05-08 09:00:00"},{"dt":1588939200,"main":{"temp":22.87,"feels_like":19.92,"temp_min":22.87,"temp_max":22.87,"pressure":1018,"sea_level":1018,"grnd_level":1013,"humidity":33,"temp_kf":0},"weather":[{"id":802,"main":"Clouds","description":"scattered clouds","icon":"03d"}],"clouds":{"all":31},"wind":{"speed":2.82,"deg":68},"sys":{"pod":"d"},"dt_txt":"2020-05-08 12:00:00"},{"dt":1588950000,"main":{"temp":23.36,"feels_like":20.49,"temp_min":23.36,"temp_max":23.36,"pressure":1017,"sea_level":1017,"grnd_level":1012,"humidity":36,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"clouds":{"all":69},"wind":{"speed":3.25,"deg":73},"sys":{"pod":"d"},"dt_txt":"2020-05-08 15:00:00"},{"dt":1588960800,"main":{"temp":21.14,"feels_like":18.5,"temp_min":21.14,"temp_max":21.14,"pressure":1015,"sea_level":1015,"grnd_level":1010,"humidity":46,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"clouds":{"all":80},"wind":{"speed":3.48,"deg":72},"sys":{"pod":"d"},"dt_txt":"2020-05-08 18:00:00"},{"dt":1588971600,"main":{"temp":17.93,"feels_like":15.74,"temp_min":17.93,"temp_max":17.93,"pressure":1016,"sea_level":1016,"grnd_level":1010,"humidity":58,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"clouds":{"all":72},"wind":{"speed":3.02,"deg":73},"sys":{"pod":"n"},"dt_txt":"2020-05-08 21:00:00"},{"dt":1588982400,"main":{"temp":15.85,"feels_like":13.42,"temp_min":15.85,"temp_max":15.85,"pressure":1014,"sea_level":1014,"grnd_level":1009,"humidity":65,"temp_kf":0},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04n"}],"clouds":{"all":82},"wind":{"speed":3.27,"deg":61},"sys":{"pod":"n"},"dt_txt":"2020-05-09 00:00:00"},{"dt":1588993200,"main":{"temp":14.5,"feels_like":12.29,"temp_min":14.5,"temp_max":14.5,"pressure":1012,"sea_level":1012,"grnd_level":1007,"humidity":70,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"clouds":{"all":100},"wind":{"speed":2.88,"deg":70},"sys":{"pod":"n"},"dt_txt":"2020-05-09 03:00:00"},{"dt":1589004000,"main":{"temp":14.78,"feels_like":12.12,"temp_min":14.78,"temp_max":14.78,"pressure":1010,"sea_level":1010,"grnd_level":1005,"humidity":68,"temp_kf":0},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04d"}],"clouds":{"all":100},"wind":{"speed":3.46,"deg":107},"sys":{"pod":"d"},"dt_txt":"2020-05-09 06:00:00"},{"dt":1589014800,"main":{"temp":15.44,"feels_like":13.21,"temp_min":15.44,"temp_max":15.44,"pressure":1009,"sea_level":1009,"grnd_level":1004,"humidity":70,"temp_kf":0},"weather":[{"id":500,"main":"Rain","description":"light rain","icon":"10d"}],"clouds":{"all":100},"wind":{"speed":3.25,"deg":78},"rain":{"3h":0.62},"sys":{"pod":"d"},"dt_txt":"2020-05-09 09:00:00"}],"city":{"id":2988507,"name":"Paris","coord":{"lat":48.8534,"lon":2.3488},"country":"FR","population":2138551,"timezone":7200,"sunrise":1588566274,"sunset":1588619402}}

[Wind] Returning cached data undefined

**Comment by werthdavid** [comment]
You are absolutely right!

**Comment by werthdavid** [comment]
Please try with homebridge-weather@1.12.3

**Comment by Julien-Molina** [comment]
It works very well now. Thanks a lot.
