### ISSUE TITLE
Windspeed shows as % and not m/s

### ISSUE THREAD

**Issue by mimes123** [werthdavid/homebridge-weather#32]
my sensor for windspeed shows up like humidity in HomeKit and not as m/s how do i change that ? i used the config examples in the description and used Type: windspeed

**Comment by werthdavid** [comment]
Yes that’s right. The problem is that home bridge or actually HomeKit doesn’t come with an accessory for type wind speed or any other accessory that displays m/s. So instead I used a humidity sensor that shows the m/s value as %...

**Comment by mimes123** [comment]
So it can’t be changed ?

**Comment by werthdavid** [comment]
Not at this point. Maybe HomeKit will change but for now I can’t do anything.
