### ISSUE TITLE
Get Error Code 401: Invalid API Key 

### ISSUE THREAD

**Issue by lowrents** [werthdavid/homebridge-weather#36]
Hello

I installed homebridge-weather today, unfortunately it doesn't work properly. The homebridge log says:
`body: '{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}',`

I monitor homebridge using pm2, running homebridge v1.1.6 and node v12.18.4
**plugins:**
homebridge-hue@0.11.76
homebridge-wol@4.3.0
homebridge-weather@1.12.4

I signed up and make a new key using this URL `https://home.openweathermap.org/api_keys`. Of course I waited for activation and testet the key using this URL `http://api.openweathermap.org/data/2.5/weather?q=Berlin&appid=API_KEY`. 

the output is:
`{"coord":{"lon":13.41,"lat":52.52},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"base":"stations","main":{"temp":290.41,"feels_like":289.23,"temp_min":288.71,"temp_max":292.04,"pressure":992,"humidity":77},"visibility":10000,"wind":{"speed":3.1,"deg":130},"clouds":{"all":100},"dt":1601752367,"sys":{"type":1,"id":1275,"country":"DE","sunrise":1601701876,"sunset":1601743146},"timezone":7200,"id":2950159,"name":"Berlin","cod":200}`
...so the key seems working. But I also tried a new generated API key with the same results. 

The config.json from homebridge:
```
"accessories": [
    {
                "accessory": "Weather",
                "api_key": "API_KEY",
                "locationByCoordinates": "lat:xxxxx&lon:xxxx",
                "name": "My City",
                "pollingInterval": 10
     }
]
```

I don't know how to further troubleshoot and solve my problem... Am I missing something? 

Thanks for any help!

**Comment by lowrents** [comment]
SOLVED!
how dumb... I think it was a bit too late yesterday. 
I misplaced the underscore in config.json file... so that's why the API key could not be read and was passed as "undefined" to the URL.

**Comment by werthdavid** [comment]
Glad I could help... 😆

**Comment by lowrents** [comment]
Thank's a lot 😁 great tool btw
