### ISSUE TITLE
Enhancement: High and low temperatures

### ISSUE THREAD

**Issue by sejoki** [werthdavid/homebridge-weather#4]
First of all, thank you for the plugin, it helps a lot to have some more information in HomeKit to base rules upon.

There's one thing I'm missing - daily high and low data. It would help a lot with some rules. For example, if it gets hotter than x degrees, water the plants for 10 minutes, if it's lower than x, turn on for 5 minutes. Or if it's warmer than y degrees, don't open the blinds in the morning.

Some rules for planning ahead don't need live data all the time or wouldn't even make sense to rely on live data. If it's going to be a hot day, I don't want the sun to burn through the windows in the morning, heating up the place, but if it's a moderate day it's alright. Also, I'd water the plants during the night (just a garden pump with a rain barrel hooked up to an eve switch), but if it's a cloudy/cold day, I don't need them to run as long.
Chance of rain would be awesome, but that would be hard to implement with home kit rules, because it would absolutely positively have to rain that day to not run the watering system.

High/low temperatures would go a long way though. They would have to be hidden/not in the favourites section to avoid confusion, but it would be nice to have that information.

**Comment by werthdavid** [comment]
Sounds interesting, will check what I can do
