### ISSUE TITLE
Max temperature is reduced on evening

### ISSUE THREAD

**Issue by qubiack** [werthdavid/homebridge-weather#42]
I assume that the idea of creating a forecast Max/Min is a little bit different than Max is working. 

For example:
2pm - Acual 26 - Max 28
3pm - Actual 28 - Max 28
5pm - Actual 26 - Max 26
8pm - Actual 24 - Max 24
10pm - Actual 22 - Max 22

Is it any way to have it stable and keep Max the whole day as 28?

**Comment by werthdavid** [comment]
Hmm well as this plugin is using the "hourly forecast 4 days" API and not the "daily forecast 16 days" I fear that this is not possible right away.
An idea would be to set `"pollingInterval": 1440`
Then it would be updated only once per day

**Comment by qubiack** [comment]
I'm not a HomeKit developer and I never read about the structure and available memory so definitely I don't have knowledge of it and I just guessing. 
Maybe it will be possible to compare today's max temperature with some cache and update it only if the new is higher than the previous one until the end of the day (just as an option to max temperature). It will be also a good feature for the min temperature (for somebody) but in my climate isn't change anything :) 

Dealing it with `pollingInterval` doesn't solve this issue because it will depend on the moment of the day when it is fetched. So each restart of Homebridge after the update will have an influence on the time to fetch new data and updating after 8.00 pm will be always wrong.
