### ISSUE TITLE
Temperature Sensor not showing in automation tab in Home App

### ISSUE THREAD

**Issue by gerritfries** [werthdavid/homebridge-weather#5]
Thanks a lot for this plugin! I really like it a lot, since there is no need for a real sensor to check the temperature outside. The sensor is showing up at the Room i created, but I can't use it for automation purpose in Home App - the sensor option is still greyed out. I thought it would act like an actual sensor so I could make an automation like "temperature >30°C close blinds".

**Comment by werthdavid** [comment]
Hey,

I have to check on that. Will see what I can do.

**Comment by werthdavid** [comment]
Atm I don't have an iPad running at iOS 10 or an Apple TV so it's kinda hard to say when I can do further investigation on that topic...

**Comment by gerritfries** [comment]
Thank you so far! It seems it's not supported by Apple's Home App. With "Elgato Eve" everything works as expected.

**Comment by friko21** [comment]
This was discussed here:
https://github.com/KhaosT/HAP-NodeJS/issues/375

It looks like an mistake in Home app.
