### ISSUE TITLE
No polling?

### ISSUE THREAD

**Issue by futuretap** [werthdavid/homebridge-weather#9]
Looks like the plugin doesn't work as a source for trigger rules. I created a rule that switches on a heater when it's too cold. That rule is only executed when I open the Home app, but not in the background.

This actually works with the `homebridge-wunderground` plugin which has a configurable polling interval.

Can you add a polling mechanism as well?

**Comment by werthdavid** [comment]
I'll check out that plugin as soon as I have some spare time

**Comment by futuretap** [comment]
Thanks for the quick implementation, looks good!
